export interface Transaction {
  transactionId: string;
  accountHolder: string;
  transactionType: "Credit" | "Debit";
  amount: number;
  transactionDate: string;
  reference: string;
  status: "Completed" | "Pending" | "Failed";
}

export const transactions: Transaction[] = [
  {
    transactionId: "TXN001",
    accountHolder: "Yared Mesele",
    transactionType: "Credit",
    amount: 2500,
    transactionDate: "2024-11-01",
    reference: "INV1001",
    status: "Completed",
  },
  {
    transactionId: "TXN002",
    accountHolder: "Gutema Fite",
    transactionType: "Debit",
    amount: 1500,
    transactionDate: "2024-11-03",
    reference: "BILL2002",
    status: "Pending",
  },
  {
    transactionId: "TXN003",
    accountHolder: "Gemechu Bulti",
    transactionType: "Credit",
    amount: 3200,
    transactionDate: "2024-11-05",
    reference: "SAL3003",
    status: "Completed",
  },
  {
    transactionId: "TXN004",
    accountHolder: "Bob Brown",
    transactionType: "Debit",
    amount: 500,
    transactionDate: "2024-11-06",
    reference: "BILL4004",
    status: "Failed",
  },
  {
    transactionId: "TXN005",
    accountHolder: "Charlie Davis",
    transactionType: "Credit",
    amount: 1200,
    transactionDate: "2024-11-08",
    reference: "REF5005",
    status: "Completed",
  },
  {
    transactionId: "TXN006",
    accountHolder: "Emily White",
    transactionType: "Debit",
    amount: 800,
    transactionDate: "2024-11-09",
    reference: "BILL6006",
    status: "Pending",
  },
  {
    transactionId: "TXN006",
    accountHolder: "Emily White",
    transactionType: "Debit",
    amount: 800,
    transactionDate: "2024-11-09",
    reference: "BILL6006",
    status: "Pending",
  },
  {
    transactionId: "TXN006",
    accountHolder: "Emily White",
    transactionType: "Debit",
    amount: 800,
    transactionDate: "2024-11-09",
    reference: "BILL6006",
    status: "Pending",
  },
  {
    transactionId: "TXN006",
    accountHolder: "Emily White",
    transactionType: "Debit",
    amount: 800,
    transactionDate: "2024-11-09",
    reference: "BILL6006",
    status: "Pending",
  },
  {
    transactionId: "TXN006",
    accountHolder: "Emily White",
    transactionType: "Debit",
    amount: 800,
    transactionDate: "2024-11-09",
    reference: "BILL6006",
    status: "Pending",
  },
  {
    transactionId: "TXN006",
    accountHolder: "Emily White",
    transactionType: "Debit",
    amount: 800,
    transactionDate: "2024-11-09",
    reference: "BILL6006",
    status: "Pending",
  },
  {
    transactionId: "TXN006",
    accountHolder: "Emily White",
    transactionType: "Debit",
    amount: 800,
    transactionDate: "2024-11-09",
    reference: "BILL6006",
    status: "Pending",
  },
  {
    transactionId: "TXN006",
    accountHolder: "Emily White",
    transactionType: "Debit",
    amount: 800,
    transactionDate: "2024-11-09",
    reference: "BILL6006",
    status: "Pending",
  },
  {
    transactionId: "TXN006",
    accountHolder: "Emily White",
    transactionType: "Debit",
    amount: 800,
    transactionDate: "2024-11-09",
    reference: "BILL6006",
    status: "Pending",
  },
  {
    transactionId: "TXN006",
    accountHolder: "Emily White",
    transactionType: "Debit",
    amount: 800,
    transactionDate: "2024-11-09",
    reference: "BILL6006",
    status: "Pending",
  },
  {
    transactionId: "TXN006",
    accountHolder: "Emily White",
    transactionType: "Debit",
    amount: 800,
    transactionDate: "2024-11-09",
    reference: "BILL6006",
    status: "Pending",
  },
];
